Repository coala/projects, pull requests merged in 2018-05, with the labels that each got.

#568 .travis.yml: Enable travis-buddy
  .travis.yml
Labels: process/approved, size/XS

#562 Add issue link to project description
  _projects/commit-content-checks.md
Labels: process/approved, size/XS

#572 Change blog URL for RJ722
  reports/RJ722.md
Labels: process/pending review, size/XS

#581 vulture.md: Fix broken link
  _projects/vulture.md
Labels: process/approved, size/XS

#575 coala_language_server.md: Update project details
  _projects/coala_language_server.md
Labels: process/approved, size/S

#579 git_task_list.md: Add Git Task List project
  _projects/git_task_list.md
Labels: process/approved, size/S

#577 go_bears_on_bsd.md: Add Go on BSD project
  _projects/go_bears_on_bsd.md
Labels: process/pending review, size/S
