Repository coala/projects, pull requests merged in 2018-08, with the labels that each got.

#602 .coafile: Add two new sections for checking line character length.
  .coafile
  _projects/add_repo_license.md
  _projects/aspects.md
  _projects/assign_issues.md
  _projects/automate_dependency_repology.md
  _projects/bear_updates.md
  _projects/coala_cli.md
  _projects/commit_based_perftest.md
  _projects/convert_bear_to_aspects.md
  _projects/debug_profile.md
  _projects/documentation_extraction.md
  _projects/extend_linter_integration.md
  _projects/generic_bears.md
  _projects/gitmate_gitlab.md
  _projects/gitmate_jira.md
  _projects/gitmate_plugins.md
  _projects/gitmate_testing.md
  _projects/go_bears_on_bsd.md
  _projects/implement_aspects.md
  _projects/implement_metrics_for_coala.md
  _projects/improve_diff_handling.md
  _projects/improve_installation.md
  _projects/integrate-pyflakes-AST.md
  _projects/jetbrains-ide-plugin.md
  _projects/nested_languages.md
  _projects/newcomer_metrics.md
  _projects/nextgen_action_system.md
  _projects/optimize_caching.md
  _projects/roberta_external_source.md
  _projects/use_coala.md
  _projects/use_coala_2.md
  _projects/use_coala_3.md
  _projects/vulture.md
Labels: process/pending review, size/L

#609 report.md: Make GSoC year dynamic
  _layouts/report.md
Labels: process/pending review, size/XS

#626 commit_based_perftest.md: Fix docstring typo
  _projects/commit_based_perftest.md
Labels: difficulty/newcomer, importance/low, process/approved, size/XS

#618 reports: Add li-boxuan's GSoC report
  reports/li-boxuan.md
Labels: process/pending review, size/M

#610 reports: Add pareksha's GSoC report
  reports/pareksha.md
Labels: process/pending review, size/M

#631 reports/example.md: Update GSoC report template
  reports/example.md
Labels: difficulty/low, importance/high, process/pending review, size/XS

#633 Create reports collection
  _config.yml
  _reports/AlexMaxim.md
  _reports/HemangKumar.md
  _reports/MeetMangukiya.md
  _reports/NaveenKumarSangi.md
  _reports/RahulJha.md
  _reports/adhikasp.md
  _reports/example.md
  _reports/li-boxuan.md
  _reports/pareksha.md
  _reports/satwikkansal.md
Labels: process/pending review, size/S

#634 .coafile: Ignore _reports dir
  .coafile
Labels: process/pending review, size/XS

#611 reports: Add Vaibhav Rai GSoC report
  _reports/RaiVaibhav.md
Labels: process/approved, size/S

#617 report: Add virresh's GSoC report
  _reports/virresh.md
Labels: process/pending review, size/M

#635 reports: Add palash25.md
  _reports/palash25.md
Labels: process/approved, size/S

#632 reports: Add ksdme's GSoC report
  _reports/ksdme.md
Labels: process/approved, size/M

#612 reports: Add Kriti Rohilla'a GSoC report
  _reports/kriti21.md
Labels: process/approved, size/S

#630 reports: Add anctartica's GSoC report
  _reports/saksham.md
Labels: process/approved, size/M

#614 report: Add macbox7 GSoC report
  _reports/macbox7.md
Labels: process/pending review, size/M

#622 reports: Add report for RJ722 2018
  _reports/RJ722.md
Labels: process/approved, size/M

#638 _reports/example.md: Add date
  _reports/example.md
Labels: process/approved, size/XS

#639 _reports/RJ722.md: Update report for RJ722
  _reports/RJ722.md
Labels: process/approved, size/XS

#641 Add ishanSrt's report
  _reports/ishanSrt.md
Labels: process/pending review, size/S

#646 Update ishanSrt's report
  _reports/ishanSrt.md
Labels: process/approved, size/S

#647 _reports: Add yzgyyang's GSoC report
  _reports/GuangyuanYang.md
Labels: process/approved, size/S

#650 reports.html: Create report listing
  reports.html
Labels: difficulty/low, process/approved, size/XS

#651 _projects: Update status of GSoC 2018 projects
  _projects/antlr_v4.md
  _projects/automate_dependency_repology.md
  _projects/automate_vulture_whitelist.md
  _projects/bear_updates.md
  _projects/coala_language_server.md
  _projects/commit-content-checks.md
  _projects/convert_bear_to_aspects.md
  _projects/corobo_enhancement.md
  _projects/debug_profile.md
  _projects/editor_support.md
  _projects/gitmate_jira.md
  _projects/gitmate_plugins.md
  _projects/go_bears_on_bsd.md
  _projects/improve_installation.md
  _projects/integrate-pyflakes-AST.md
  _projects/meta_review.md
  _projects/nested_languages.md
  _projects/newcomer_metrics.md
  _projects/optimize_caching.md
  _projects/quickstart_green_mode.md
Labels: difficulty/newcomer, importance/medium, process/approved, size/S
