Repository coala/projects, pull requests merged in 2018-11, with the labels that each got.

#686 FAQ: Finish Indonesian translation
  data/locale/id/faq/coala-will-apply-for-gsoc.md
Labels: process/approved, size/XS

#685 projects.html: Added GSoC project reports link
  partials/tabs/projects.html
Labels: difficulty/newcomer, process/pending review, size/XS

#689 reports: Display sha256sum on webpage
  _layouts/report.md
  _reports/AlexMaxim.md
  _reports/HemangKumar.md
  _reports/MeetMangukiya.md
  _reports/NaveenKumarSangi.md
  _reports/RahulJha.md
  _reports/adhikasp.md
  _reports/macbox7.md
  _reports/satwikkansal.md
  resources/css/style.css
Labels: difficulty/low, difficulty/newcomer, importance/critical, process/approved, size/S
