Repository coala/projects, pull requests merged in 2018-03, with the labels that each got.

#436 assign_issues: Mark completed
  _projects/assign_issues.md
Labels: process/approved, size/XS

#435 Update the CI1, CI2 , & CI3 tasks to refer to 2017
  _projects/use_coala.md
  _projects/use_coala_2.md
  _projects/use_coala_3.md
Labels: process/approved, size/XS

#467 bear_updates.md: Fix typo
  _projects/bear_updates.md
Labels: process/approved, size/XS

#471 FAQ: Fix broken link
  _faq/application_template.md
Labels: process/approved, size/XS

#476 application_template.md: Fix typo
  _faq/application_template.md
Labels: process/approved, size/XS

#481 antlr_v4.md: Add aptrishu as mentor
  _projects/antlr_v4.md
Labels: process/approved, size/XS

#478 .ruby-version: 2.2.3 -> 2.4.3
  .ruby-version
Labels: process/approved, size/XS

#483 antlr_v4.md: Add mentor corona10
  _projects/antlr_v4.md
Labels: process/approved, size/XS

#485 mentors.html: Update for GSoC 2018
  partials/tabs/mentors.html
Labels: process/approved, size/XS

#482 improve_diff_handling.md: Add mentor satwikkansal
  _projects/improve_diff_handling.md
Labels: process/approved, size/XS

#486 Fixes #375: Center project name in modal
  resources/css/style.css
Labels: process/approved, size/XS

#475 nextgen_action_system.md: New project proposal
  _projects/nextgen_action_system.md
Labels: process/approved, size/XS

#496 app.js: Exclude mentors on completed projects
  resources/js/app.js
Labels: process/approved, size/XS

#505 gitmate_jira.md: Mark status as in_progress
  _projects/gitmate_jira.md
Labels: process/approved, size/XS

#500 application_template.md: Updates the year
  _faq/application_template.md
Labels: process/approved, size/XS

#507 application_template.md: Add a new item for username checking url
  _faq/application_template.md
Labels: process/approved, size/XS

#494 improve_diff_handling: Update description
  _projects/improve_diff_handling.md
Labels: process/approved, size/S

#514 resources/css/styles: Clickable icon on hover
  resources/css/style.css
Labels: process/approved, size/XS

#495 projects: Add coala Language Server
  _projects/coala_language_server.md
Labels: process/approved, size/XS

#489 commit-content-checks.md: New proposal
  _projects/commit-content-checks.md
Labels: Project Proposal, process/approved, size/S

#517 bear_updates: Add crowded label
  _projects/bear_updates.md
Labels: process/approved, size/XS

#509 application_template.md: Delete duplicate
  _faq/application_template.md
Labels: process/approved, size/XS

#523 Marked Some Project Ideas as crowded
  _projects/antlr_v4.md
  _projects/commit-content-checks.md
  _projects/debug_profile.md
  _projects/improve_installation.md
Labels: process/approved, size/XS

#515 faq: Replace dead links to projects.js
  _faq/own_project_idea.md
  _faq/thesis.md
Labels: importance/low, process/approved, size/XS

#526 projects.html: Add more project ideas link
  partials/tabs/projects.html
Labels: process/approved, size/XS

#528 Add 'status: completed' to all GCI projects
  _projects/add_repo_license.md
  _projects/use_coala.md
  _projects/use_coala_2.md
  _projects/use_coala_3.md
Labels: process/approved, size/XS

#464 Update aspects project description
  _projects/convert_bear_to_aspects.md
Labels: Project Proposal, process/approved, size/XS

#524 application_template: Add element for upstream commits
  _faq/application_template.md
Labels: process/approved, size/XS

#513 GitMate plugins project idea
  _projects/gitmate_plugins.md
Labels: Project Proposal, process/approved, size/XS

#534 Mark two project ideas as crowded
  _projects/coala_language_server.md
  _projects/newcomer_metrics.md
Labels: process/approved, size/XS

#536 _projects: Add automate_dependacy_repology.md
  _projects/automate_dependacy_repology.md
Labels: process/approved, size/XS

#535 corobo_enhancement: Add corobo enhancement project
  _projects/corobo_enhancement.md
Labels: process/approved, size/XS

#533 gitmate_plugins.md: Add auto-assign plugin
  _projects/gitmate_plugins.md
Labels: process/approved, size/XS

#527 high_involvement_status.md: Add FAQ about status high involvement
  _faq/high_involvement_status.md
Labels: process/approved, size/XS

#537 newcomer_metrics.md: Add prnvdixit to mentor's list
  _projects/newcomer_metrics.md
Labels: process/approved, size/XS

#539 mentor_obligations.md: Update faq
  _faq/mentor_obligations.md
Labels: process/approved, size/XS

#542 .gitignore: Add .DS_Store
  .gitignore
Labels: process/approved, size/XS
