Repository coala/projects, pull requests merged in 2018-10, with the labels that each got.

#665 moban: Sync moban templates
  .gitignore
Labels: process/pending review, size/XS

#666 add-repo-license.md: Replace broken link
  _projects/add-repo-license.md
Labels: difficulty/low, process/approved, size/XS

#661 .editorconfig: Add new file
  .editorconfig
Labels: difficulty/low, process/approved, size/XS

#667 .gitignore: Sync moban
  .gitignore
Labels: process/approved, size/XS

#656 Update adhikasp.md
  _reports/adhikasp.md
Labels: difficulty/newcomer, importance/low, process/approved, size/S

#675 coala-will-apply-for-gsoc-2018.md: Remove references to specific years
  _faq/coala-will-apply-for-gsoc-2018.md
  _faq/coala-will-apply-for-gsoc.md
Labels: difficulty/newcomer, process/approved, size/XS

#668 authorPatchCollector.py: Add GSOC patch collector
  tools/authorPatchCollector.py
Labels: difficulty/low, enhancement, process/approved, size/S

#680 reports.html: Create dynamic report listing by year
  reports.html
Labels: difficulty/low, initiatives/gci, process/approved, size/XS

#682 application-template.md: Make GSoC application template dynamic
  _config.yml
  _faq/application-template.md
Labels: difficulty/low, initiatives/gci, process/approved, size/XS
