Repository coala/projects, pull requests merged in 2019-08, with the labels that each got.

#719 _projects: Add "Enhance Website Architecture" project to projects list
  _projects/enhance-and-improve-coala-community-and-projects-website.md
Labels: Project Proposal, process/approved, process/pending review, size/S

#720 Add Support TOML Project to projects list
  _projects/standardised-file-format.md
Labels: Project Proposal, process/pending review, size/XS

#736 index.html: Add a navbar
  index.html
  resources/css/style.css
  resources/js/app.js
  screenshots/logo.png
Labels: process/approved

#693 _faq: Add details about cEPs to faq
  _faq/cep-and-its-importance.md
Labels: difficulty/low, importance/medium, process/approved, size/XS

#715 index.html: Update footer design
  _config.yml
  index.html
  resources/css/style.css
Labels: process/wip, size/XS

#712 app.js: Sort projects acc. to status in scope
  partials/tabs/projects.html
  resources/js/app.js
Labels: bug, difficulty/low, importance/low, process/approved, size/XS

#721 projects.html: Add hyperlink to the mentors' name
  partials/tabs/projects.html
Labels: difficulty/newcomer, process/pending review, size/XS

#722 _projects: add git-bug to the list of projects
  _projects/git-bug.md
Labels: process/pending review, size/XS

#739 Add chay2199 report
  _reports/chay2199.md
Labels: process/wip

#731 projects.html: Add filters for searching projects
  index.html
  partials/tabs/projects.html
  resources/css/style.css
  resources/js/app.js
  resources/js/directives/faqs.js
  resources/js/directives/mentors.js
  resources/js/directives/projects.js
  resources/js/directives/students.js
Labels: process/wip
